name: Auto Commit and Push

on:
  push:
    branches:
      - main  # Changes on the main branch
  schedule:
    - cron: "0 * * * *"  # Runs every hour

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Make Changes
        run: |
          # Commands for automatic changes like editing files
          echo "Changes made automatically" > myfile.txt

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto commit update"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}